# _config.yml
remote_theme: mmistakes/minimal-mistakes # Replace with your chosen theme's user/repo name

title: Psychology 101 Notes # Still good to have
description: An overview and notes for introductory psychology. # Still good to have
